refresh_interval = 1000

[[modules]]
name = "sysinfo"
instance = "0"
format = "CPU: {cpu_usage:{:4.1}}% Mem: {mem_usage:{:4.1}}% Load: {load_avg_1:{:4.2}}/{load_avg_5:{:4.2}}/{load_avg_15:{:4.2}}"
html_escape = false

[modules.on_click]
Left = [
    "foot",
    "htop",
]

[[modules]]
name = "battery"
instance = "0"
format = "Bat:{state_of_charge:{:4.0}}% Health:{state_of_health:{:3.0}}%"
html_escape = false

[[modules]]
name = "pactl"
instance = "0"
format = "Vol:{volume:{:3}}%{muted}"
html_escape = true

[modules.on_click]
Left = ["pavucontrol"]
WheelUp = [
    "pactl",
    "set-sink-volume",
    "@DEFAULT_SINK@",
    "+1%",
]
Right = [
    "pactl",
    "set-sink-mute",
    "@DEFAULT_SINK@",
    "toggle",
]
WheelDown = [
    "pactl",
    "set-sink-volume",
    "@DEFAULT_SINK@",
    "-1%",
]
[[modules]]
name = "nmcli"
instance = "0"
format = "Net: {name} -{signal}"
html_escape = false

[[modules]]
name = "date"
instance = "0"
format = "%F %X"
html_escape = false
